on:
push:
branches:
- main # Change this to your main branch name
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: actions/checkout@v2
- name: Set Up Node.js
uses: actions/setup-node@v2
with:
node-version: '14'
- name: Install Dependencies
run: npm install
- name: Generate Readme
run: npm run generate-readme # Replace with your build command
- name: Commit and Push Changes
run: |
git config --global user.name 'Farhakousar1601'
git config --global user.email 'Farhakousar1601@gmail.com'
git commit -am "Update profile readme" --allow-empty
git push
